// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyANsjsH8JWQParetWTvwqdapcxFSiTzGlo',
    appId: '1:504032250342:web:1cd4cc4b0d9e35bf68ae27',
    messagingSenderId: '504032250342',
    projectId: 'bookverse-project',
    authDomain: 'bookverse-project.firebaseapp.com',
    storageBucket: 'bookverse-project.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBQGjOw1uCh5P0RwycSHRoYZTIq8lqbP7w',
    appId: '1:504032250342:android:9b890f21f42f295668ae27',
    messagingSenderId: '504032250342',
    projectId: 'bookverse-project',
    storageBucket: 'bookverse-project.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBnovw0UGS4a_WfIobwugZG669Sk7vbF40',
    appId: '1:504032250342:ios:366dbc784c94f39568ae27',
    messagingSenderId: '504032250342',
    projectId: 'bookverse-project',
    storageBucket: 'bookverse-project.firebasestorage.app',
    iosBundleId: 'com.example.bookverseProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBnovw0UGS4a_WfIobwugZG669Sk7vbF40',
    appId: '1:504032250342:ios:366dbc784c94f39568ae27',
    messagingSenderId: '504032250342',
    projectId: 'bookverse-project',
    storageBucket: 'bookverse-project.firebasestorage.app',
    iosBundleId: 'com.example.bookverseProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyANsjsH8JWQParetWTvwqdapcxFSiTzGlo',
    appId: '1:504032250342:web:c271ee50119c5ab668ae27',
    messagingSenderId: '504032250342',
    projectId: 'bookverse-project',
    authDomain: 'bookverse-project.firebaseapp.com',
    storageBucket: 'bookverse-project.firebasestorage.app',
  );
}
